[project]
name = "nwnee-data-utilities"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nwn>=0.0.14",
    "regex>=2024.11.6",
]
