[project]
name = "nwnee-data-utilities"
version = "1.0.0"
description = "A collection of utilities for Neverwinter Nights: Enhanced Edition (NWNEE) data handling"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nwn>=0.0.14",
    "regex>=2024.11.6",
]
