name: Build and Release Executables

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history needed for git log

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka "nwn>=0.0.14" "regex>=2024.11.6"

    - name: Compile Python scripts with Nuitka
      run: |
        mkdir -p dist
        for script in src/*.py; do
          name=$(basename "$script")
          if [ "$name" != "ndu.py" ]; then
            nuitka --onefile --output-dir=dist "$script"
          fi
        done
      shell: bash

    - name: Archive executables by platform
      run: |
        platform="${{ runner.os }}"
        archive_name="nwnee-data-utilities-${platform,,}-x64.zip"
        cd dist
        zip -r "../$archive_name" ./*
        cd ..

    - name: Prepare curated source package
      run: |
        mkdir -p source_package/src
        cp src/*.py source_package/src/
        cp README.txt pyproject.toml source_package/
        zip -r "nwnee-data-utilities-src-${{ github.ref_name || 'dev' }}.zip" source_package

    - name: Install GitHub CLI
      if: github.event_name == 'release'
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Upload release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          nwnee-data-utilities-*-x64.zip
          nwnee-data-utilities-src-${{ github.ref_name }}.zip
          CHANGELOG.txt
